CONSUMER_KEY: fzwWCvA2hmY0KHT9w0gri7uOk
CONSUMER_KEY_SECRET: 1OSYEFCRzntG3Z1HCChGSMjMXCvoCg0DZmCp1IelJlhomiEt5j
ACCESS_TOKEN: 60920627-3y6s9KaQPS6cmCAur6Rnak0flUNh4FxRuDJC73y6p
ACCESS_TOKEN_SECRET: QY6Jfy945i4VHQMa5nDozXMRvI6ZvjGiBtHJZtpWY14Qz
CODEA_TAG_API_TOKEN: 9398fe2d4d0f7cc9b3fc7036edff991c